spring.application.name=event_sync
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=PassNassaIWord
spring.datasource.url=jdbc:postgresql://localhost:5432/event_sync_db