spring.application.name=event_sync
server.port=${PORT:8080}

# Neon PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${NEON_DATABASE_URL}
spring.datasource.username=${NEON_DATABASE_USERNAME}
spring.datasource.password=${NEON_DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.session.store-type=jdbc

spring.session.jdbc.initialize-schema=never

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.db.enabled=true

jwt.secret=${JWT_SECRET:aT7rK9pL2xQ5vY8cB3nM6wE1zF4gH9jK2lR5tU8xW1yZ4}
jwt.expiration=${JWT_EXPIRATION:86400000}
