spring.application.name=event_sync

# PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/eventsync_db
spring.datasource.username=postgres
spring.datasource.password=

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc

server.port=${PORT:8080}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.db.enabled=true

# JWT Configuration (valeurs temporaires pour le développement)
jwt.secret=aT7rK9pL2xQ5vY8cB3nM6wE1zF4gH9jK2lR5tU8xW1yZ4
jwt.expiration=86400000
