name: Keep Aiven Alive

on:
  schedule:
    # S'exécute toutes les 10 minutes
    - cron: '*/10 * * * *'
  # Permet de déclencher le ping manuellement depuis l'onglet Actions
  workflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest
    environment: aiven-db 

    steps:
      - name: Ping PostgreSQL Aiven
        run: |
          # Installation du client postgresql
          sudo apt-get update && sudo apt-get install -y postgresql-client

          # Récupération de l'URL depuis votre variable GitHub
          RAW_URL="${{ vars.SPRING_DATASOURCE_URL }}"

          # Suppression du préfixe 'jdbc:' pour psql
          CLEAN_URL=$(echo "$RAW_URL" | sed 's/^jdbc://')

          echo "Connexion en cours vers Aiven..."

          # Connexion directe à l'URL globale en imposant l'utilisateur de vos variables
          PGPASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}" psql \
            "$CLEAN_URL" \
            -U "${{ vars.SPRING_DATASOURCE_USERNAME }}" \
            -c "SELECT 1;"
