name: Keep Aiven Alive

on:
  schedule:
    # S'exécute toutes les 10 minutes
    - cron: '*/10 * * * *'
  # Permet de déclencher le ping manuellement depuis l'onglet Actions
  workflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest
    # ATTENTION : Remplacez "production" par le nom exact de votre environnement
    # si vous l'avez nommé différemment sur l'interface GitHub
    environment: aiven-db

    steps:
      - name: Ping PostgreSQL Aiven
        run: |
          # Installation du client postgresql
          sudo apt-get update && sudo apt-get install -y postgresql-client

          # Connexion directe à Aiven en transmettant le mot de passe et l'URL simplifiée
          PGPASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}" psql \
            "${{ vars.DATABASE_URL }}" \
            -U "${{ vars.SPRING_DATASOURCE_USERNAME }}" \
            -c "SELECT 1;"
